### ISSUE TITLE
String relational operator ]] not supported

### ISSUE THREAD

**Issue by kurtlebreton** [jewuma/mumps-debug#12]
Using the ]] operator isn't recognized as valid M code and instead highlights with a red squiggly error in the VSCode editor.
I'm using YottaDB. The code is correct. It compiles and runs properly.
Please see [YottaDB docs](https://docs.yottadb.com/ProgrammersGuide/langfeat.html#string-relational-operators) for reference.

**Comment by kurtlebreton** [comment]
```
YDB>WRITE "A"]]"B"
0
YDB>WRITE "B"]]"A"
1
```

> binary operator causes M to produce a TRUE if the first expression lexically sorts after the second expression in the subscript collation sequence

**Comment by jewuma** [comment]
Thank you for your report. This should be fixed now.

**Comment by kurtlebreton** [comment]
Confirming this is fixed in latest version.
Many thanks for your efforts in making this project :-)
