### ISSUE TITLE
Extension error next to debugger launch

### ISSUE THREAD

**Issue by gowillyf** [jewuma/mumps-debug#14]
[vscodeextension-error.txt](https://github.com/jewuma/mumps-debug/files/9197107/vscodeextension-error.txt)
Try to use the extension from Windows PC connecting to a Linux PC with GT.M installed.
On debugger launch, the MDEBUG server displays 'Debugger connected'. Then, nothing more happens.
Would you mind sharing a tutorial with screenshots please.

**Comment by jewuma** [comment]
Is it possible to post the routine you want to debug?
Usually the processs is straightforward: the lauch.json has to be saved like the example in README.
You have the routine you want to debug on the acive editor page and click on "PLAY".
The execution should stop at the first instruction.

**Comment by gowillyf** [comment]
[basic.m.txt](https://github.com/jewuma/mumps-debug/files/9199471/basic.m.txt)
I'm using a really basic routine with just one label for testing purpose.
On VSCode debugger, only Pause, Restart and Stop buttons are enabled.

**Comment by jewuma** [comment]
My guess is that your filename is not correct - BASIC.m.txt instead of BASIC.m

Can you run your program with mumps -r BASIC ?

BTW you should add a quit after d testResults(10)

**Comment by gowillyf** [comment]
Unfortunately, no. I've added extension '.txt' just to overcome GITHUB upload rule.
I've added a QUIT call to the main routine.
Compilation and run are working fine :
```
gowillyf@FRV02:~/src/Scripts
$ mumps basic.m 
gowillyf@FRV02:~/src/Scripts
$ mumps -r basic
10
gowillyf@FRV02:~/src/Scripts
$ mumps -r BASIC
%GTM-E-ZLINKFILE, Error while zlinking "BASIC"
%GTM-E-FILENOTFND, File BASIC.m not found
%GTM-E-FILENOTFND, File BASIC.o not found
gowillyf@FRV02:~/src/Scripts
```
I've also a little bit hacked the MDEBUG server to have more details on the different exchange.

```
gowillyf@FRV02:~/src/Scripts
$ gtm 'd ^MDEBUG'
*MDEBUG LAUNCHING*
*MDEBUG INIT*
*MDEBUG DEBUG-Port opened*
*MDEBUG KEY* CONNECT|h1658995299000|::ffff:172.31.248.179
Debugger connected: h1658995299000  |TCP|9000|332423
 332423 |TCP|9000|332423
CLEARBP;/home/gowillyf/Projects/Scripts/basic.m
SETBP;/home/gowillyf/Projects/Scripts/basic.m;3;
REQUESTBP
CLEARBP;/home/gowillyf/Projects/Scripts/basic2.m
SETBP;/home/gowillyf/Projects/Scripts/basic2.m;7;
REQUESTBP
ERRCHK
SETBP;/home/gowillyf/Projects/Scripts/basic.m;0;
REQUESTBP
START;/home/gowillyf/Projects/Scripts/basic.m
basic+2^basic 332423 |TCP|9000|332423
Sending Vars
```
As you can see, I'm able to set or unset the breakpoints but still unable to really debug step by step.

**Comment by jewuma** [comment]
Does MDEBUG hang then? Can you stop it with Ctrl-C and Write $ZPOS?
I could reproduce problems when renaming BASIC.m to basic.m but they were gone after restart of VS-Code.
I'm sorry I can't help immediatly but without the chance to reporduce it it's not so easy.
Do you edit the routine via Samba share?

**Comment by gowillyf** [comment]
MDEBUG does not seem to hang. I can set/unset many breakpoints and the data sent to MDEBUG are OK.
Here is the result after stopping the MDEBUG :

```
$ gtm 'zwr $ZPOS'
$ZPOSITION="midm+17^midm"
```
Currently, I'm using VSCode Remote facilities with SSH to modify the code on my Linux PC. Compilation is done through VSCode terminal.

**Comment by jewuma** [comment]
Well, it seems, the debugger is not designed for this configuration. The debugger has no direct access to the remote-file.
There ssem to be a workaround here:
[https://code.visualstudio.com/docs/remote/troubleshooting]()   (see sshfs)
which may help but seem to be complicated.
Or if you like you can try editing and debugging over a samba share which should work.

**Comment by gowillyf** [comment]
[errorreport-3.txt](https://github.com/jewuma/mumps-debug/files/9218132/errorreport-3.txt)
Remote access is or was a way to overcome problem using the extension directly on Linux PC.
If I try to use it locally, and looking at extension logs, I've found some errors when VSCode try to activate the extensions 'mumps-debug' or 'dsilin.mumps' (see logs).
I would really appreciate to be able to use your extension for debugging MUMPS code.

**Comment by jewuma** [comment]
I've uploaded a small demo (look at files demovideo.webm). It shows how the debugger works local on a linux mint machine. maybe that helps.

**Comment by gowillyf** [comment]
Thanks for sharing this video. I was using the extension correctly.
Finally, I get it to work modifying some lines in MDEBUG routine (I'm on Ubuntu 20.04 and GT.M).
Great job.

**Comment by jewuma** [comment]
Thank you for your comment. Can you share your modifications? Maybe it helps other users too.

**Comment by gowillyf** [comment]
[MDEBUGModified.m.txt](https://github.com/jewuma/mumps-debug/files/9288957/MDEBUGModified.m.txt)
Here is the routine with few modifications.

**Comment by jewuma** [comment]
I've cleaned MDEBUG a bit. It runs fine here.
