### ISSUE TITLE
Bug on VSCode 1.74.3 : line highlighted do not match the code executed.

### ISSUE THREAD

**Issue by gowillyf** [jewuma/mumps-debug#15]
When trying to debug using VSCode 1.74.3, I've always a mismatch between the highlighted line and the step executed on the MUMPS file.
Other point : when I try to step into another routine, the highlihted line is the first one of my current file, and so on.

**Comment by jewuma** [comment]
Please try the new version 1.1.4,
I hope the problems are solved.

**Comment by gowillyf** [comment]
The problem is solved.
Thanks for your update.
