### ISSUE TITLE
Some optional syntax is unrecognised with TSTART and OPEN 

### ISSUE THREAD

**Issue by kurtlebreton** [jewuma/mumps-debug#19]
I've noticed that the following fail syntax check:

1. The optional arguments used to enable restarting of a transaction e.g:
 - `TSTART *`
 - `TSTART *:(SERIAL)`
 - `TSTART *:SERIAL`

2. The optional arguments for opening a socket
 - `ZBFSIZE=`
 - `ZIBFSIZE=`

e.g
`OPEN socdev:(LISTEN=listen:NOWRAP:NODELIMITER:ATTACH=attach:CHSET=chset:ZBFSIZE=ReadSize:ZIBFSIZE=SystemSize):1:"SOCKET"`

Please find quick links to corresponding documentation below:

1. [Yotta ZBFSIZE](https://docs.yottadb.net/ProgrammersGuide/ioproc.html#zbfsize)
2. [Yotta ZIBFSIZE](https://docs.yottadb.net/ProgrammersGuide/ioproc.html#zibfsize)
4. [Yotta TStart](https://docs.yottadb.net/ProgrammersGuide/commands.html#tstart)

**Comment by jewuma** [comment]
Issue should be fixed with Version 1.1.7
Thank you for reporting

**Comment by kurtlebreton** [comment]
Thank you, I've updated to 1.1.7
