### ISSUE TITLE
VS Code debug commands not operational 

### ISSUE THREAD

**Issue by DavidStables** [jewuma/mumps-debug#22]
Just installed this excellent extension latest 1.1.8 on windows 11, latest VS code,  with ubuntu 22.04 and yottaDB

MDEBUG running and launch.json has been configured and routines in place

On running VS code debug (F5) debugger connects but no further code is executed except that
F11 generates "INTO" and processes one line, but no other commands from the editor get through.
Have tried writing out the commands as they arrive server side (uncommenting READLOOP+2) and only the following seem to be accepted
F5 triggers CLEARBP,SETBP,REQUESTBP, ERRCHK, START which gets to the D ^routine command and then freezes as if a breakpoint had been found but nothing on the VS code end (and the breakpoint is further on)

F11 triggers INTO  which steps one line correctly i.e. is running as one would expect. So its communicating

The debug menu buttons on VS code are greyed out i.e. I don't think the commands are getting through or debug session not quite getting set up on the VS side?

However, the Extension settings shows errors namely uncaught errors "Cannot read properties of undefined (reading 'length')"
These get added to with each attempt at F5 START debugging.
I have tried downgrading to 1.0.0 but no difference I think.

Any ideas/ thoughts welcome.

**Comment by jewuma** [comment]
This looks to me as if the "localRoutinesPath" in the launch.json is not ok.
MDEBUG passes the routine-names like xyz back to the editor. 
if  "localRoutinesPath"="X:/" VS-Code tries to open "X:/xyz.m" if that doesn't work debugging doesn't work.
if Yotta and VS-Code runs both on a linux machine maybe "localRoutinesPath" could be "/var/lib/routines/"
Maybe I should add some checks here.
HTH
Jens

**Comment by DavidStables** [comment]
Indeed, turned out to be a syntax error with using the wsl.localhost path in launch which works well at the M end but misread at the VS code end. Most convenient way was to map the wsl folder path to a a drive letter as per your example.
Thanks for your help.
