### ISSUE TITLE
Saving file indents whole file.

### ISSUE THREAD

**Issue by shanedewitt** [jewuma/mumps-debug#23]
I will open a mumps routine file and make a small change on 1 line. I then save the file and the entire file gets re-indented to to a tab or 4 spaces. Before the save, the file was only indented 1 space.

Is there a way to turn off this behavior?

**Comment by jewuma** [comment]
Try this: Goto file/settings/settings and paste this in the search field: `@id:editor.formatOnSave @lang:mumps form`

uncheck the box. Tell me if it works for you.

**Comment by shanedewitt** [comment]
Yes this works. Thanks.
